name: 'binfx410_genomics'
version: '1.0.0'
config-version: 2

profile: 'binfx410_athena'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  binfx410_genomics:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +file_format: parquet
      +table_type: iceberg

vars:
  # Change to your student bucket
  s3_bucket: "binfx410-datalake-your-student-id"
  athena_database: "binfx410_sra"
  aws_region: "us-east-1"
